// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5XhoMbQ-rIKLwCS5pBqmnzKRW_4vP_J8',
    appId: '1:509316971428:web:16e2b04d20b52df8b99f31',
    messagingSenderId: '509316971428',
    projectId: 'sekp-e625d',
    authDomain: 'sekp-e625d.firebaseapp.com',
    storageBucket: 'sekp-e625d.firebasestorage.app',
    measurementId: 'G-KRS5ENJ429',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYbVuRMOOxoE46RTUOh8xrLJz-m-ro8_I',
    appId: '1:509316971428:android:4f9a2e13b046640bb99f31',
    messagingSenderId: '509316971428',
    projectId: 'sekp-e625d',
    storageBucket: 'sekp-e625d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUXz6zhTXPVhm9x2WC1SBdunQpAmXJXvA',
    appId: '1:509316971428:ios:0f773213a00622adb99f31',
    messagingSenderId: '509316971428',
    projectId: 'sekp-e625d',
    storageBucket: 'sekp-e625d.firebasestorage.app',
    iosBundleId: 'com.example.sekp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUXz6zhTXPVhm9x2WC1SBdunQpAmXJXvA',
    appId: '1:509316971428:ios:0f773213a00622adb99f31',
    messagingSenderId: '509316971428',
    projectId: 'sekp-e625d',
    storageBucket: 'sekp-e625d.firebasestorage.app',
    iosBundleId: 'com.example.sekp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5XhoMbQ-rIKLwCS5pBqmnzKRW_4vP_J8',
    appId: '1:509316971428:web:7ea9f95324115531b99f31',
    messagingSenderId: '509316971428',
    projectId: 'sekp-e625d',
    authDomain: 'sekp-e625d.firebaseapp.com',
    storageBucket: 'sekp-e625d.firebasestorage.app',
    measurementId: 'G-Y0VXG14XMD',
  );
}
